<a href="https://colab.research.google.com/github/soorichu/colab/blob/master/deepmath_chap3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow
구글 브레인 AI 패키지. 
1. 딥러닝 모델을 그래프ㅡ 방식으로 표현함으로써 다양한 딥러닝 모델 구축 가능
1. 자동으로 미분 계산 처리해주어 역전파법(Backpropagation) 구현이 생략 가능
1. 텐서 보드를 사용하여 딥러닝 학습 진행 상황을 웹서버를 통해 간편한 모니터링 가능
1. 적은 코드 내용 수정으로 그래픽카드를 사용한 가속 가능

In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [0]:
import numpy as np
import tensorflow as tf

## Tensor 
텐서는 벡터와 행렬의 N차원 배열을 일반화한 개념. 딥러닝에 필요한 데이터와 계산된 값들은 모두 예외 없이 텐서로 표현된다. 모든 텐서에는 Data Type과 Shape가 있다. 

Data Type은 float32, float64, int32, int64, bool, string 등 기본적인 타입들이 있다. 한 텐서는 모두 같은 데이터 타입이 구성되어야 한다.

Shape는 각 차원의 크기를 알려주는 튜플. N차원 텐서라면 튜플의 길이는 N이 된다. 그리고 이 때 N을 Rank라고 부른다. 다음은 특정한 렝크를 갖는 텐서의 경우를 부르는 수학적 용어를 소개하는 표

| Rank | Math |
|------|------|
|0 | 스칼라 |
|1|벡터|
|2|행렬|
|3|3-텐서(Cube of numbers)|
|N|N-텐서|

텐서플로를 사용할 때 직접 텐서 클래스를 사용하는 경우는 드물고, Constant, Placeholder, Variable 등 텐서 클래스를 상속 박는 자식 클래스들을 통해 그래프를 구성한다.

## Graph
텐서플로를 사용하는 코드는 '그래프 만들기'와 '만든 그래프에 데이터 흘려 보내기' 두 부분으로 나눌 수 있다.
텐서플로에서는 노드에 해당하는 클래스가 연산(Operation)이고, 에지(화살표)에 해당되는 클래스가 텐서(Tensor)이다. 딥러닝 모델을 데이터가 들어와 노드를 거치며 변하는 그래프를 표현한다. 

### 텐서T(Tensor) + 흐름(Flow) = TensorFlow

In [4]:
hc = tf.constant('Hello World')
print(hc)

Tensor("Const:0", shape=(), dtype=string)


In [5]:
sess= tf.Session()
output = sess.run(hc)
print(output)

b'Hello World'


## 주요 타입
1. Constant
1. Placeholder
1. Variable

### 1. Constant

In [8]:
hc = tf.constant("Hello world")
with tf.Session() as sess:
  output = sess.run(hc)
print(output)

b'Hello world'


### 2. Placeholder

In [11]:
hp = tf.placeholder(tf.string, shape=None)
with tf.Session() as sess:
  output = sess.run(hp, feed_dict={hp:'Hello World'})
print(output)

Hello World


In [0]:
x = tf.placeholder(tf.string, shape=None)
y = tf.placeholder(tf.int32, shape=None)
z = tf.placeholder(tf.float32, shape=None)

In [13]:
with tf.Session() as sess:
  output = sess.run(x, feed_dict={x:'Hello World', y:123, z:45.67})
print(output)

Hello World


In [0]:
with tf.Session() as sess:
  output = sess.run([x, y, z], feed_dict={x:'hello world', y:123, z:45.67})

In [15]:
xval, yval, zval = output
print(xval, yval, zval)

hello world 123 45.67


In [20]:
x = tf.placeholder(tf.int32, shape=(2))
with tf.Session() as sess:
  output = sess.run(x, feed_dict={x: [1,2]})
print(output)

[1 2]


In [22]:
x = tf.placeholder(tf.int32, shape=(2, 3))
with tf.Session() as sess:
  output = sess.run(x, feed_dict={x: [[1,2,3], [4,5,6]]})
print(output)

[[1 2 3]
 [4 5 6]]


### Variable
Variable 타입은 딥러닝에서 가장 핵심적인 역할을 한다. 딥러닝 모델을 학습한다는 것은 가장 좋은 딥러닝 모델을 만드는 Variable을 찾는다고 말할 수 있다.

In [23]:
x = tf.Variable(10)
print(x)

<tf.Variable 'Variable:0' shape=() dtype=int32_ref>
ERROR! Session/line number was not unique in database. History logging moved to new session 61


In [25]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
print(output)

[[1 2 3]
 [4 5 6]]


In [28]:
x = tf.Variable(10)
init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  output = sess.run(x)
print(output)

10


In [32]:
x = tf.constant(10)
y = tf.constant(2)
z = x / y
w = z - 1
print(x, y, z, w)

Tensor("Const_2:0", shape=(), dtype=int32) Tensor("Const_3:0", shape=(), dtype=int32) Tensor("truediv:0", shape=(), dtype=float64) Tensor("sub:0", shape=(), dtype=float64)


In [33]:
with tf.Session() as sess:
  output = sess.run([z, w])
print(output)

[5.0, 4.0]


## 스칼라 덧셈
### $z = x + y$

In [38]:
x = tf.constant(10)
y = tf.constant(2)
z = x + y
with tf.Session() as sess:
  output = sess.run(z)
print(output)

12


In [39]:
x = tf.placeholder(tf.int32)
y = tf.placeholder(tf.int32)
z = x + y

with tf.Session() as sess:
  output = sess.run(z, feed_dict={x:10, y:2})
print(output)

12


In [41]:
x = tf.Variable(10, dtype=tf.int32)
y = tf.Variable(2, dtype=tf.int32)
z = x + y
int = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  output = sess.run(z, feed_dict={x:10, y:2})
print(output)

12


In [42]:
x = tf.constant(4.0)
z = tf.square(x)

with tf.Session() as sess:
  output = sess.run(z)
  print(output)

16.0


In [43]:
x = tf.placeholder(tf.float64)
z = tf.square(x)

with tf.Session() as sess:
  output = sess.run(z, feed_dict={x:4.0})
print(output)

16.0


In [44]:
x = tf.Variable(4.0)
z = tf.square(x) # pow(x, 3), squared_difference(x, y), sqrt(x), pow(x, 1.0/3.0), reduce_min(x)

init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  output = sess.run(z)
print(output)

16.0


In [45]:
x = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=tf.float64)
y = tf.reduce_sum(x)
z = tf.reduce_mean(x)

with tf.Session() as sess:
  output = sess.run([y, z])
print(output)

[55.0, 5.5]
